// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

// Retrieve the binding value, as type PythonSdkDev
func (r *Binding) AsPythonSDKDev() *PythonSDKDev { // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:15:6)
	q := r.query.Select("asPythonSdkDev")

	return &PythonSDKDev{
		query: q,
	}
}

// Retrieve the binding value, as type PythonSdkDevDocs
func (r *Binding) AsPythonSDKDevDocs() *PythonSDKDevDocs { // python-sdk-dev (../../../../toolchains/python-sdk-dev/docs.go:9:6)
	q := r.query.Select("asPythonSdkDevDocs")

	return &PythonSDKDevDocs{
		query: q,
	}
}

// Retrieve the binding value, as type PythonSdkDevPythonTest
func (r *Binding) AsPythonSDKDevPythonTest() *PythonSDKDevPythonTest { // python-sdk-dev (../../../../toolchains/python-sdk-dev/test.go:38:6)
	q := r.query.Select("asPythonSdkDevPythonTest")

	return &PythonSDKDevPythonTest{
		query: q,
	}
}

// Retrieve the binding value, as type PythonSdkDevPythonTestMatrix
func (r *Binding) AsPythonSDKDevPythonTestMatrix() *PythonSDKDevPythonTestMatrix { // python-sdk-dev (../../../../toolchains/python-sdk-dev/test.go:11:6)
	q := r.query.Select("asPythonSdkDevPythonTestMatrix")

	return &PythonSDKDevPythonTestMatrix{
		query: q,
	}
}

// Create or update a binding of type PythonSdkDevDocs in the environment
func (r *Env) WithPythonSDKDevDocsInput(name string, value *PythonSDKDevDocs, description string) *Env { // python-sdk-dev (../../../../toolchains/python-sdk-dev/docs.go:9:6)
	assertNotNil("value", value)
	q := r.query.Select("withPythonSdkDevDocsInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired PythonSdkDevDocs output to be assigned in the environment
func (r *Env) WithPythonSDKDevDocsOutput(name string, description string) *Env { // python-sdk-dev (../../../../toolchains/python-sdk-dev/docs.go:9:6)
	q := r.query.Select("withPythonSdkDevDocsOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Create or update a binding of type PythonSdkDev in the environment
func (r *Env) WithPythonSDKDevInput(name string, value *PythonSDKDev, description string) *Env { // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:15:6)
	assertNotNil("value", value)
	q := r.query.Select("withPythonSdkDevInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired PythonSdkDev output to be assigned in the environment
func (r *Env) WithPythonSDKDevOutput(name string, description string) *Env { // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:15:6)
	q := r.query.Select("withPythonSdkDevOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Create or update a binding of type PythonSdkDevPythonTest in the environment
func (r *Env) WithPythonSDKDevPythonTestInput(name string, value *PythonSDKDevPythonTest, description string) *Env { // python-sdk-dev (../../../../toolchains/python-sdk-dev/test.go:38:6)
	assertNotNil("value", value)
	q := r.query.Select("withPythonSdkDevPythonTestInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Create or update a binding of type PythonSdkDevPythonTestMatrix in the environment
func (r *Env) WithPythonSDKDevPythonTestMatrixInput(name string, value *PythonSDKDevPythonTestMatrix, description string) *Env { // python-sdk-dev (../../../../toolchains/python-sdk-dev/test.go:11:6)
	assertNotNil("value", value)
	q := r.query.Select("withPythonSdkDevPythonTestMatrixInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired PythonSdkDevPythonTestMatrix output to be assigned in the environment
func (r *Env) WithPythonSDKDevPythonTestMatrixOutput(name string, description string) *Env { // python-sdk-dev (../../../../toolchains/python-sdk-dev/test.go:11:6)
	q := r.query.Select("withPythonSdkDevPythonTestMatrixOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired PythonSdkDevPythonTest output to be assigned in the environment
func (r *Env) WithPythonSDKDevPythonTestOutput(name string, description string) *Env { // python-sdk-dev (../../../../toolchains/python-sdk-dev/test.go:38:6)
	q := r.query.Select("withPythonSdkDevPythonTestOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// A toolchain to develop the Dagger Python SDK
type PythonSDKDev struct { // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:15:6)
	query *querybuilder.Selection

	id            *ID
	release       *Void
	releaseDryRun *Void
	sourcePath    *string
	typecheck     *Void
}
type WithPythonSDKDevFunc func(r *PythonSDKDev) *PythonSDKDev

// With calls the provided function with current PythonSDKDev.
//
// This is useful for reusability and readability by not breaking the calling chain.
func (r *PythonSDKDev) With(f WithPythonSDKDevFunc) *PythonSDKDev {
	return f(r)
}

func (r *PythonSDKDev) WithGraphQLQuery(q *querybuilder.Selection) *PythonSDKDev {
	return &PythonSDKDev{
		query: q,
	}
}

// PythonSDKDevBuildOpts contains options for PythonSDKDev.Build
type PythonSDKDevBuildOpts struct {
	//
	// The version for the distribution package
	//
	//
	// Default: "0.0.0"
	Version string // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:262:2)
}

// Build the Python SDK client library package for distribution
func (r *PythonSDKDev) Build(opts ...PythonSDKDevBuildOpts) *Container { // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:259:1)
	q := r.query.Select("build")
	for i := len(opts) - 1; i >= 0; i-- {
		// `version` optional argument
		if !querybuilder.IsZeroValue(opts[i].Version) {
			q = q.Arg("version", opts[i].Version)
		}
	}

	return &Container{
		query: q,
	}
}

// Regenerate the core Python client library
func (r *PythonSDKDev) ClientLibrary() *Changeset { // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:162:1)
	q := r.query.Select("clientLibrary")

	return &Changeset{
		query: q,
	}
}

// Python container to develop Python SDK
func (r *PythonSDKDev) DevContainer() *Container { // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:17:2)
	q := r.query.Select("devContainer")

	return &Container{
		query: q,
	}
}

// Preview the reference documentation
func (r *PythonSDKDev) Docs() *PythonSDKDevDocs { // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:300:1)
	q := r.query.Select("docs")

	return &PythonSDKDevDocs{
		query: q,
	}
}

// PythonSDKDevFormatOpts contains options for PythonSDKDev.Format
type PythonSDKDevFormatOpts struct {
	//
	// List of files or directories to check
	//
	Paths []string // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:122:2)
}

// Format source files
func (r *PythonSDKDev) Format(opts ...PythonSDKDevFormatOpts) *Changeset { // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:119:1)
	q := r.query.Select("format")
	for i := len(opts) - 1; i >= 0; i-- {
		// `paths` optional argument
		if !querybuilder.IsZeroValue(opts[i].Paths) {
			q = q.Arg("paths", opts[i].Paths)
		}
	}

	return &Changeset{
		query: q,
	}
}

// A unique identifier for this PythonSdkDev.
func (r *PythonSDKDev) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *PythonSDKDev) XXX_GraphQLType() string {
	return "PythonSdkDev"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *PythonSDKDev) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *PythonSDKDev) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *PythonSDKDev) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *PythonSDKDev) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = PythonSDKDev{query: selectNode(dag.query, id, "PythonSdkDev")}
	return nil
}

// PythonSDKDevLintOpts contains options for PythonSDKDev.Lint
type PythonSDKDevLintOpts struct {
	//
	// List of files or directories to check
	//
	Paths []string // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:110:2)
}

// Check for linting errors
func (r *PythonSDKDev) Lint(opts ...PythonSDKDevLintOpts) *Container { // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:107:1)
	q := r.query.Select("lint")
	for i := len(opts) - 1; i >= 0; i-- {
		// `paths` optional argument
		if !querybuilder.IsZeroValue(opts[i].Paths) {
			q = q.Arg("paths", opts[i].Paths)
		}
	}

	return &Container{
		query: q,
	}
}

// PythonSDKDevLintDocsSnippetsOpts contains options for PythonSDKDev.LintDocsSnippets
type PythonSDKDevLintDocsSnippetsOpts struct {
	Workspace *Directory // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:99:2)
}

// Lint the Python snippets in the documentation
func (r *PythonSDKDev) LintDocsSnippets(opts ...PythonSDKDevLintDocsSnippetsOpts) *Container { // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:91:1)
	q := r.query.Select("lintDocsSnippets")
	for i := len(opts) - 1; i >= 0; i-- {
		// `workspace` optional argument
		if !querybuilder.IsZeroValue(opts[i].Workspace) {
			q = q.Arg("workspace", opts[i].Workspace)
		}
	}

	return &Container{
		query: q,
	}
}

// PythonSDKDevProvisionOpts contains options for PythonSDKDev.Provision
type PythonSDKDevProvisionOpts struct {
	//
	// _EXPERIMENTAL_DAGGER_RUNNER_HOST value
	//
	RunnerHost string // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:312:2)
}

func (r *PythonSDKDev) Provision(cliBin *File, opts ...PythonSDKDevProvisionOpts) *Container { // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:306:1)
	assertNotNil("cliBin", cliBin)
	q := r.query.Select("provision")
	for i := len(opts) - 1; i >= 0; i-- {
		// `runnerHost` optional argument
		if !querybuilder.IsZeroValue(opts[i].RunnerHost) {
			q = q.Arg("runnerHost", opts[i].RunnerHost)
		}
	}
	q = q.Arg("cliBin", cliBin)

	return &Container{
		query: q,
	}
}

// PythonSDKDevPublishOpts contains options for PythonSDKDev.Publish
type PythonSDKDevPublishOpts struct {
	//
	// The version for the distribution package to publish
	//
	//
	// Default: "0.0.0"
	Version string // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:276:2)
	//
	// The URL of the upload endpoint (empty means PyPI)
	//
	URL string // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:279:2)
}

// Publish Python SDK client library to PyPI
func (r *PythonSDKDev) Publish(token *Secret, opts ...PythonSDKDevPublishOpts) *Container { // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:271:1)
	assertNotNil("token", token)
	q := r.query.Select("publish")
	for i := len(opts) - 1; i >= 0; i-- {
		// `version` optional argument
		if !querybuilder.IsZeroValue(opts[i].Version) {
			q = q.Arg("version", opts[i].Version)
		}
		// `url` optional argument
		if !querybuilder.IsZeroValue(opts[i].URL) {
			q = q.Arg("url", opts[i].URL)
		}
	}
	q = q.Arg("token", token)

	return &Container{
		query: q,
	}
}

// PythonSDKDevReleaseOpts contains options for PythonSDKDev.Release
type PythonSDKDevReleaseOpts struct {
	DryRun bool // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:227:2)

	PypiRepo string // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:230:2)

	PypiURL string // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:233:2)

	PypiToken *Secret // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:236:2)
}

// Release the Python SDK
func (r *PythonSDKDev) Release(ctx context.Context, sourceTag string, opts ...PythonSDKDevReleaseOpts) error { // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:220:1)
	if r.release != nil {
		return nil
	}
	q := r.query.Select("release")
	for i := len(opts) - 1; i >= 0; i-- {
		// `dryRun` optional argument
		if !querybuilder.IsZeroValue(opts[i].DryRun) {
			q = q.Arg("dryRun", opts[i].DryRun)
		}
		// `pypiRepo` optional argument
		if !querybuilder.IsZeroValue(opts[i].PypiRepo) {
			q = q.Arg("pypiRepo", opts[i].PypiRepo)
		}
		// `pypiUrl` optional argument
		if !querybuilder.IsZeroValue(opts[i].PypiURL) {
			q = q.Arg("pypiUrl", opts[i].PypiURL)
		}
		// `pypiToken` optional argument
		if !querybuilder.IsZeroValue(opts[i].PypiToken) {
			q = q.Arg("pypiToken", opts[i].PypiToken)
		}
	}
	q = q.Arg("sourceTag", sourceTag)

	return q.Execute(ctx)
}

// Test the publishing process
func (r *PythonSDKDev) ReleaseDryRun(ctx context.Context) error { // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:208:1)
	if r.releaseDryRun != nil {
		return nil
	}
	q := r.query.Select("releaseDryRun")

	return q.Execute(ctx)
}

func (r *PythonSDKDev) SourcePath(ctx context.Context) (string, error) { // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:19:2)
	if r.sourcePath != nil {
		return *r.sourcePath, nil
	}
	q := r.query.Select("sourcePath")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Supported Python versions
func (r *PythonSDKDev) SupportedVersions(ctx context.Context) ([]string, error) { // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:21:2)
	q := r.query.Select("supportedVersions")

	var response []string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// PythonSDKDevTestPublishOpts contains options for PythonSDKDev.TestPublish
type PythonSDKDevTestPublishOpts struct {
	//
	// The version for the distribution package to publish
	//
	//
	// Default: "0.0.0"
	Version string // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:294:2)
}

// Test the publishing of the Python SDK client library to TestPyPI
func (r *PythonSDKDev) TestPublish(token *Secret, opts ...PythonSDKDevTestPublishOpts) *Container { // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:289:1)
	assertNotNil("token", token)
	q := r.query.Select("testPublish")
	for i := len(opts) - 1; i >= 0; i-- {
		// `version` optional argument
		if !querybuilder.IsZeroValue(opts[i].Version) {
			q = q.Arg("version", opts[i].Version)
		}
	}
	q = q.Arg("token", token)

	return &Container{
		query: q,
	}
}

// Tests returns the test matrix keyed by Python version.
//
// A collection is used because versions are homogeneous data, not distinct
// schema roles. This lets another Python project supply its own version set
// without adding one field or function for each version.
func (r *PythonSDKDev) Tests() *PythonSDKDevPythonTestMatrix { // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:156:1)
	q := r.query.Select("tests")

	return &PythonSDKDevPythonTestMatrix{
		query: q,
	}
}

// Run the type checker (mypy)
// FIXME: this is not included as an automated check. Should it?
func (r *PythonSDKDev) Typecheck(ctx context.Context) error { // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:134:1)
	if r.typecheck != nil {
		return nil
	}
	q := r.query.Select("typecheck")

	return q.Execute(ctx)
}

// Mount a directory on the base container
func (r *PythonSDKDev) WithDirectory(source *Directory) *PythonSDKDev { // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:143:1)
	assertNotNil("source", source)
	q := r.query.Select("withDirectory")
	q = q.Arg("source", source)

	return &PythonSDKDev{
		query: q,
	}
}

func (r *PythonSDKDev) Workspace() *Directory { // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:18:2)
	q := r.query.Select("workspace")

	return &Directory{
		query: q,
	}
}

// AsNode returns this PythonSDKDev as a Node.
// This is a local type conversion — no GraphQL call.
func (r *PythonSDKDev) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

type PythonSDKDevDocs struct { // python-sdk-dev (../../../../toolchains/python-sdk-dev/docs.go:9:6)
	query *querybuilder.Selection

	id *ID
}

func (r *PythonSDKDevDocs) WithGraphQLQuery(q *querybuilder.Selection) *PythonSDKDevDocs {
	return &PythonSDKDevDocs{
		query: q,
	}
}

// Build the documentation
func (r *PythonSDKDevDocs) Build() *Directory { // python-sdk-dev (../../../../toolchains/python-sdk-dev/docs.go:15:1)
	q := r.query.Select("build")

	return &Directory{
		query: q,
	}
}

// A unique identifier for this PythonSdkDevDocs.
func (r *PythonSDKDevDocs) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *PythonSDKDevDocs) XXX_GraphQLType() string {
	return "PythonSdkDevDocs"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *PythonSDKDevDocs) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *PythonSDKDevDocs) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *PythonSDKDevDocs) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *PythonSDKDevDocs) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = PythonSDKDevDocs{query: selectNode(dag.query, id, "PythonSdkDevDocs")}
	return nil
}

// PythonSDKDevDocsPreviewOpts contains options for PythonSDKDevDocs.Preview
type PythonSDKDevDocsPreviewOpts struct {
	//
	// The port to bind the web preview for the built docs
	//
	//
	// Default: 8000
	Bind int // python-sdk-dev (../../../../toolchains/python-sdk-dev/docs.go:28:2)
}

// Build and preview the documentation in the browser
func (r *PythonSDKDevDocs) Preview(opts ...PythonSDKDevDocsPreviewOpts) *Service { // python-sdk-dev (../../../../toolchains/python-sdk-dev/docs.go:25:1)
	q := r.query.Select("preview")
	for i := len(opts) - 1; i >= 0; i-- {
		// `bind` optional argument
		if !querybuilder.IsZeroValue(opts[i].Bind) {
			q = q.Arg("bind", opts[i].Bind)
		}
	}

	return &Service{
		query: q,
	}
}

// AsNode returns this PythonSDKDevDocs as a Node.
// This is a local type conversion — no GraphQL call.
func (r *PythonSDKDevDocs) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

// PythonTest runs a project's tests with one Python version.
type PythonSDKDevPythonTest struct { // python-sdk-dev (../../../../toolchains/python-sdk-dev/test.go:38:6)
	query *querybuilder.Selection

	id      *ID
	run     *Void
	slow    *Void
	unit    *Void
	version *string
}

func (r *PythonSDKDevPythonTest) WithGraphQLQuery(q *querybuilder.Selection) *PythonSDKDevPythonTest {
	return &PythonSDKDevPythonTest{
		query: q,
	}
}

// A unique identifier for this PythonSdkDevPythonTest.
func (r *PythonSDKDevPythonTest) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *PythonSDKDevPythonTest) XXX_GraphQLType() string {
	return "PythonSdkDevPythonTest"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *PythonSDKDevPythonTest) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *PythonSDKDevPythonTest) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *PythonSDKDevPythonTest) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *PythonSDKDevPythonTest) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = PythonSDKDevPythonTest{query: selectNode(dag.query, id, "PythonSdkDevPythonTest")}
	return nil
}

// Run the pytest command.
func (r *PythonSDKDevPythonTest) Run(ctx context.Context, args []string) error { // python-sdk-dev (../../../../toolchains/python-sdk-dev/test.go:59:1)
	if r.run != nil {
		return nil
	}
	q := r.query.Select("run")
	q = q.Arg("args", args)

	return q.Execute(ctx)
}

// Run Python slow tests.
func (r *PythonSDKDevPythonTest) Slow(ctx context.Context) error { // python-sdk-dev (../../../../toolchains/python-sdk-dev/test.go:48:1)
	if r.slow != nil {
		return nil
	}
	q := r.query.Select("slow")

	return q.Execute(ctx)
}

// Run Python unit tests.
func (r *PythonSDKDevPythonTest) Unit(ctx context.Context) error { // python-sdk-dev (../../../../toolchains/python-sdk-dev/test.go:54:1)
	if r.unit != nil {
		return nil
	}
	q := r.query.Select("unit")

	return q.Execute(ctx)
}

// The Python version to test against
func (r *PythonSDKDevPythonTest) Version(ctx context.Context) (string, error) { // python-sdk-dev (../../../../toolchains/python-sdk-dev/test.go:43:2)
	if r.version != nil {
		return *r.version, nil
	}
	q := r.query.Select("version")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// AsNode returns this PythonSDKDevPythonTest as a Node.
// This is a local type conversion — no GraphQL call.
func (r *PythonSDKDevPythonTest) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

// PythonTestMatrix is a reusable test matrix keyed by Python version.
type PythonSDKDevPythonTestMatrix struct { // python-sdk-dev (../../../../toolchains/python-sdk-dev/test.go:11:6)
	query *querybuilder.Selection

	id *ID
}
type WithPythonSDKDevPythonTestMatrixFunc func(r *PythonSDKDevPythonTestMatrix) *PythonSDKDevPythonTestMatrix

// With calls the provided function with current PythonSDKDevPythonTestMatrix.
//
// This is useful for reusability and readability by not breaking the calling chain.
func (r *PythonSDKDevPythonTestMatrix) With(f WithPythonSDKDevPythonTestMatrixFunc) *PythonSDKDevPythonTestMatrix {
	return f(r)
}

func (r *PythonSDKDevPythonTestMatrix) WithGraphQLQuery(q *querybuilder.Selection) *PythonSDKDevPythonTestMatrix {
	return &PythonSDKDevPythonTestMatrix{
		query: q,
	}
}

// Get a test suite for one Python version.
func (r *PythonSDKDevPythonTestMatrix) Get(key string) *PythonSDKDevPythonTest { // python-sdk-dev (../../../../toolchains/python-sdk-dev/test.go:30:1)
	q := r.query.Select("get")
	q = q.Arg("key", key)

	return &PythonSDKDevPythonTest{
		query: q,
	}
}

// A unique identifier for this PythonSdkDevPythonTestMatrix.
func (r *PythonSDKDevPythonTestMatrix) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *PythonSDKDevPythonTestMatrix) XXX_GraphQLType() string {
	return "PythonSdkDevPythonTestMatrix"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *PythonSDKDevPythonTestMatrix) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *PythonSDKDevPythonTestMatrix) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *PythonSDKDevPythonTestMatrix) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *PythonSDKDevPythonTestMatrix) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = PythonSDKDevPythonTestMatrix{query: selectNode(dag.query, id, "PythonSdkDevPythonTestMatrix")}
	return nil
}

// Python versions in this matrix
func (r *PythonSDKDevPythonTestMatrix) Keys(ctx context.Context) ([]string, error) { // python-sdk-dev (../../../../toolchains/python-sdk-dev/test.go:14:2)
	q := r.query.Select("keys")

	var response []string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Items in the current subset, in the same order as `keys`.
func (r *PythonSDKDevPythonTestMatrix) List(ctx context.Context) ([]PythonSDKDevPythonTest, error) {
	q := r.query.Select("list")

	q = q.Select("id")

	type list struct {
		Id ID
	}

	convert := func(fields []list) []PythonSDKDevPythonTest {
		out := []PythonSDKDevPythonTest{}

		for i := range fields {
			val := PythonSDKDevPythonTest{id: &fields[i].Id}
			val.query = selectNode(q.Root(), fields[i].Id, "PythonSdkDevPythonTest")
			out = append(out, val)
		}

		return out
	}
	var response []list

	q = q.Bind(&response)

	err := q.Execute(ctx)
	if err != nil {
		return nil, err
	}

	return convert(response), nil
}

// Restrict the collection to an exact subset of keys.
func (r *PythonSDKDevPythonTestMatrix) Subset(keys []string) *PythonSDKDevPythonTestMatrix {
	q := r.query.Select("subset")
	q = q.Arg("keys", keys)

	return &PythonSDKDevPythonTestMatrix{
		query: q,
	}
}

// AsNode returns this PythonSDKDevPythonTestMatrix as a Node.
// This is a local type conversion — no GraphQL call.
func (r *PythonSDKDevPythonTestMatrix) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

// PythonSDKDevOpts contains options for Query.PythonSDKDev
type PythonSDKDevOpts struct {
	//
	// A workspace containing the SDK source code and other relevant files
	//
	WorkspaceDir *Directory // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:47:2)

	// Default: "sdk/python"
	SourcePath string // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:50:2)
	//
	// Python versions to test
	//
	//
	// Default: ["3.14","3.13","3.12","3.11","3.10"]
	PythonVersions []string // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:53:2)
	//
	// A docker config file with credentials to install on clients.
	//
	ClientDockerConfig *Secret // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:56:2)
	//
	// Workspace forwarded to engine-dev for VCS stamping. Auto-injected on a
	// direct call; dependencies don't inherit it, so callers must forward it.
	//
	Ws *Workspace // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:59:2)
}

// A toolchain to develop the Dagger Python SDK
func (r *Query) PythonSDKDev(opts ...PythonSDKDevOpts) *PythonSDKDev { // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:26:1)
	q := r.query.Select("pythonSdkDev")
	for i := len(opts) - 1; i >= 0; i-- {
		// `workspaceDir` optional argument
		if !querybuilder.IsZeroValue(opts[i].WorkspaceDir) {
			q = q.Arg("workspaceDir", opts[i].WorkspaceDir)
		}
		// `sourcePath` optional argument
		if !querybuilder.IsZeroValue(opts[i].SourcePath) {
			q = q.Arg("sourcePath", opts[i].SourcePath)
		}
		// `pythonVersions` optional argument
		if !querybuilder.IsZeroValue(opts[i].PythonVersions) {
			q = q.Arg("pythonVersions", opts[i].PythonVersions)
		}
		// `clientDockerConfig` optional argument
		if !querybuilder.IsZeroValue(opts[i].ClientDockerConfig) {
			q = q.Arg("clientDockerConfig", opts[i].ClientDockerConfig)
		}
		// `ws` optional argument
		if !querybuilder.IsZeroValue(opts[i].Ws) {
			q = q.Arg("ws", opts[i].Ws)
		}
	}

	return &PythonSDKDev{
		query: q,
	}
}
